# This file was generated by GoReleaser. DO NOT EDIT.
cask "guild" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "5f46df55e36cc21b9a132081cdbd15605a2c44a17538b8116288112669a8f901"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
    on_arm do
      sha256 "8f265c3a359acbf9c8e87aa83040546e74241ffff23feafd88c899bd7e15f5e9"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
  end

  on_linux do
    on_intel do
      sha256 "515fb0c0f09cc40432dc951a333c2ca0db4a5adce16de05329f922d3a2d31f18"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
    on_arm do
      sha256 "4f99398235e019a726204b60b08876429814fab25550c94a96186780bc8b93ea"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
  end

  name "guild"
  desc "persistent cognition for AI agents — task + knowledge lifecycle"
  homepage "https://github.com/mathomhaus/guild"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "guild"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/guild"]
    end
  end

  # No zap stanza required

end
