# This file was generated by GoReleaser. DO NOT EDIT.
cask "guild" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "4c4179c824b5279d7270d01d40ca16a9a0b00d34d41c6ed01d25eabd63b81ff3"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
    on_arm do
      sha256 "fc44da4bea2c27b3245b421766654c514bf316d8648b598b57dc2c9cc1da3afc"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
  end

  on_linux do
    on_intel do
      sha256 "1bf19f7d7c1b54e84e9d54b2bea7d35c9d6129c9a4037c24ca36d84b4dd7b117"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_linux_amd64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
    on_arm do
      sha256 "57b316ef17f12e855fe943dab5eaed766e28925ba0b1adddf2d7ffcb2c418490"
      url "https://github.com/mathomhaus/guild/releases/download/v#{version}/guild_#{version}_linux_arm64.tar.gz",
        verified: "github.com/mathomhaus/guild"
    end
  end

  name "guild"
  desc "persistent cognition for AI agents — task + knowledge lifecycle"
  homepage "https://github.com/mathomhaus/guild"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "guild"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/guild"]
    end
  end

  # No zap stanza required

end
